Features/state and props access within setstate
sutrkiller/react-set-state-usage pull request #1
Opened 2017-07-03 14:26 UTC by Suzii

2017-07-03 15:11 UTC, PetrSvirak requested changes
It is all great. Really nice refactoring (one might even say beautification) and finishing of the rule. Thanks :+1: 

There are but two things: 
* It would seem a bit better to highlight `this.state.` or `this.props.` instead of whole `updater` function – it would be more straightforward, one would see all occurrences and, for longer states, it would not red half of the screen :stuck_out_tongue_closed_eyes: 
* Also, please, there should be a test for multiple usages of `this.state.` or `this.props.` or at least their combination. Could you please add one for all options?

2017-07-03 17:39 UTC, PetrSvirak approved these changes

2017-07-04 07:07 UTC, Suzii reviewed
Thanks for the changes, I think it is awesome now. I left some inline comments which you might consider, but generally it is good to go.

2017-07-04 07:13 UTC, merged

2017-07-04 07:17 UTC, PetrSvirak commented on src/utils/syntaxWalkerUtils.ts
> +export function removeParentheses(node: ts.Node){
http://www.commitstrip.com/en/2016/09/30/commit-or-die-trying/